AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 DashBoard"
Parameters:
  EnvType:
    Description: Environment type.
    Type: String
    AllowedValues:
      - testing
      - preprod
      - prod
    Default: testing
  EnvSubType:
    Description: Environment Sub type.
    Type: String
    Default: main
Resources:
 DashBoardBucket:
     Type: AWS::S3::Bucket
     Properties: 
       AccessControl: PublicRead
       WebsiteConfiguration:
         IndexDocument: index.html
       CorsConfiguration:
         CorsRules:
         - AllowedHeaders: ['*']
           AllowedMethods: [GET]
           AllowedOrigins: ['*']
           Id: myCORSRuleId1
           MaxAge: '3600'       
 CodeSourceBucket:
      Type: AWS::S3::Bucket
                          
Outputs:
  WebsiteURL:
    Value: !GetAtt [DashBoardBucket, WebsiteURL]
    Description: URL for website hosted on S3
    Export:
     Name: DashBoardURL
  WebS3:
    Value: !GetAtt [DashBoardBucket, Arn]
    Description: URL for website hosted on S3
    Export:
     Name: DashBoardBucketARN 
  CodeS3:
    Value: !GetAtt [CodeSourceBucket, Arn]
    Description: CodeSourceBucket ARN
    Export:
     Name: CodeSourceBucketARN        
  CodeS3Name:
    Value: 
      Ref: CodeSourceBucket
    Description: CodeSourceBucket Name
    Export:
     Name: CodeSourceBucketName    
  WebS3Name:
    Value: 
      Ref: DashBoardBucket
    Description: DashBoardBucket Name
    Export:
     Name: DashBoardBucketName
  DomainName:
    Description: S3 Storage Domain name
    Value:
      Fn::GetAtt:
        - DashBoardBucket
        - DomainName
    Export:
      Name:
        Fn::Join:
          - ':'
          - - DashBoardBucket
            - Ref: EnvType
            - Ref: EnvSubType
            - DomainName
