name: TestCode
on:
  push:
    branches:
    - master
    tags:        
    - '*'
    paths:
    - '**.py'
    - '*'

jobs: 
  DashBoard_Test:
    if: "contains(github.event.head_commit.message, 'DashBoard_Test')"  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cognito user setup
      run: |   
            echo ::set-env name=DASHBOARD_URL::http://scheduler-s3-dashboardbucket-1q9saw9grfgsu.s3-website-eu-west-1.amazonaws.com/
            echo ::set-env name=DASHBOARD_USER::dashboard
            echo ::set-env name=DASHBOARD_PWD::123                        
    - name: Install puppeteer jest and exec
      run: |   
            npm i puppeteer
            npm i jest
            cd DashBoard/jest/
            ls -l
            env
            ../../node_modules/jest/bin/jest.js dasboard.spec.js
#   - name: Run Jest
#      uses: stefanoeb/jest-action@1.0.2
#      with:
#       jestArgs: DashBoard/jest/dasboard.spec.js
